"""Add type in Users Table

Revision ID: a89fa07072a7
Revises: d0f517e911e7
Create Date: 2025-03-04 14:48:54.377764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89fa07072a7'
down_revision: Union[str, None] = 'd0f517e911e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    # ### end Alembic commands ###
