"""Add present to student model

Revision ID: d0f517e911e7
Revises: f53ad3b6581b
Create Date: 2025-03-04 14:23:52.340064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f517e911e7'
down_revision: Union[str, None] = 'f53ad3b6581b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('present', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'present')
    # ### end Alembic commands ###
