"""Initial migration

Revision ID: f53ad3b6581b
Revises: 
Create Date: 2025-03-04 11:50:45.489594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'f53ad3b6581b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ✅ Create `users` table with UUID and TIMESTAMP
    op.create_table(
        'users',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column('first_name', sa.String(length=50), nullable=False),
        sa.Column('last_name', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=50), nullable=False, unique=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
    )

    # ✅ Create `students` table (inherits from `users`)
    op.create_table(
        'students',
        sa.Column('id', UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete="CASCADE"), primary_key=True),
        sa.Column('grade_level', sa.String(length=50), nullable=False),
    )

    # ✅ Create `teachers` table (inherits from `users`)
    op.create_table(
        'teachers',
        sa.Column('id', UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete="CASCADE"), primary_key=True),
        sa.Column('subject', sa.String(length=50), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('users')
    # ### end Alembic commands ###

